In [16]:
import pandas as pd
import numpy as np

In [6]:
# 1. Python 라이브러리 함수를 사용하여 엑셀 파일을 불러오고, DataFrame을 출력해주세요.
df_excel = pd.read_excel("관서별 5대범죄 발생 및 검거.xlsx") #excel 불러오기

df_excel #dataframe 출력.

,관서명,소계(발생),소계(검거),살인(발생),살인(검거),강도(발생),강도(검거),강간(발생),강간(검거),절도(발생),절도(검거),폭력(발생),폭력(검거)
0,계,126401,82680,163,156,276,257,5449,5069,55307,21842,65206,55356
1,중부서,2860,1716,2,2,3,2,105,65,1395,477,1355,1170
2,종로서,2472,1589,3,3,6,5,115,98,1070,413,1278,1070
3,남대문서,2094,1226,1,0,6,4,65,46,1153,382,869,794
4,서대문서,4029,2579,2,2,5,4,154,124,1812,738,2056,1711
5,혜화서,2233,1354,3,2,5,4,96,63,1114,424,1015,861
6,용산서,3820,2483,5,5,14,14,194,173,1557,587,2050,1704
7,성북서,2237,1498,2,2,2,1,86,71,953,409,1194,1015
8,동대문서,4720,3205,5,5,13,13,173,146,1981,814,2548,2227
9,마포서,5854,3597,8,8,14,10,294,247,2555,813,2983,2519
10,영등포서,6867,4154,14,12,22,20,295,183,2964,978,3572,2961
11,성동서,3358,2123,4,4,9,8,126,119,1607,597,1612,1395
12,동작서,4074,2397,5,5,9,5,285,139,1865,661,1910,1587
13,광진서,5909,3707,4,4,14,26,240,220,3026,1277,2625,2180
14,서부서,2085,1393,2,2,2,1,70,59,819,293,1192,1038
15,강북서,4257,3113,7,8,14,13,153,126,1434,618,2649,2348
16,금천서,3781,2796,3,4,6,6,151,122,1567,888,2054,1776
17,중랑서,5193,3405,13,12,11,9,187,148,2135,829,2847,2407
18,강남서,5194,3370,3,3,15,12,300,225,2411,984,2465,2146
19,관악서,6345,3712,9,8,12,14,320,221,2706,827,3298,2642
20,강서서,5585,4190,7,8,13,13,262,191,2096,1260,3207,2718
21,강동서,5244,3171,4,3,6,8,156,123,2366,789,2712,2248
22,종암서,1917,1231,3,3,3,3,64,53,832,332,1015,840
23,구로서,5646,3502,8,6,15,11,281,164,2335,889,3007,2432
24,서초서,4183,2714,7,4,8,5,334,193,1982,905,1852,1607
25,양천서,4528,2815,3,5,6,3,120,105,1890,672,2509,2030
26,송파서,6778,4113,11,10,13,10,220,178,3239,1129,3295,2786
27,노원서,5130,3268,10,10,7,7,197,121,2193,801,2723,2329
28,방배서,1261,736,1,2,1,1,59,56,653,186,547,491
29,은평서,2660,1774,1,1,7,5,96,82,1095,418,1461,1268
30,도봉서,2664,1900,3,3,9,10,102,106,1063,478,1487,1303
31,수서서,3423,2362,10,7,6,6,149,124,1439,666,1819,1559

In [7]:
#2. 각 경찰서(관서명)를 해당 구 이름으로 매핑하여 '구별'이라는 새로운 column을 생성하고, DataFrame을 출력해주세요.
tmp = {'서대문서': '서대문구', '수서서': '강남구', '강서서': '강서구', '서초서': '서초구',
'서부서': '은평구', '중부서': '중구', '종로서': '종로구', '남대문서': '중구',
'혜화서': '종로구', '용산서': '용산구', '성북서': '성북구', '동대문서': '동대문구',
'마포서': '마포구', '영등포서': '영등포구', '성동서': '성동구', '동작서': '동작구',
'광진서': '광진구', '강북서': '강북구', '금천서': '금천구', '중랑서': '중랑구',
'강남서': '강남구', '관악서': '관악구', '강동서': '강동구', '종암서': '성북구', 
'구로서': '구로구', '양천서': '양천구', '송파서': '송파구', '노원서': '노원구', 
'방배서': '서초구', '은평서': '은평구', '도봉서': '도봉구'} #구별 컬럼 생성하기 위한 딕셔너리 데이터. 

#구별 컬럼 생성하기 위한 병합 데이터 프레임 생성 및 가공.
tmp = pd.DataFrame(tmp, index= ['구별']) #입력받은 딕셔너리를 DataFrame로 변환, 컬럼 명을 구별로 입력.
tmp = tmp.T #데이터 프레임을 가로에서 세로로 변환
tmp  = tmp.reset_index(drop=False) #index를 초기화하고 기존 index를 컬럼으로 이동
tmp = tmp.rename(columns={'index': '관서명'}) #컬럼 명을 재정의 

df2 = pd.merge(df_excel,tmp, on= '관서명', how = 'left') #df_excel에 관서명에 따라 구별 컬럼 추가. 문제 번호에 따라 df에 번호 부여
df2 = df2.fillna('구없음') #nan 값 대신에 구없음 입력. 
df2

,관서명,소계(발생),소계(검거),살인(발생),살인(검거),강도(발생),강도(검거),강간(발생),강간(검거),절도(발생),절도(검거),폭력(발생),폭력(검거),구별
0,계,126401,82680,163,156,276,257,5449,5069,55307,21842,65206,55356,구없음
1,중부서,2860,1716,2,2,3,2,105,65,1395,477,1355,1170,중구
2,종로서,2472,1589,3,3,6,5,115,98,1070,413,1278,1070,종로구
3,남대문서,2094,1226,1,0,6,4,65,46,1153,382,869,794,중구
4,서대문서,4029,2579,2,2,5,4,154,124,1812,738,2056,1711,서대문구
5,혜화서,2233,1354,3,2,5,4,96,63,1114,424,1015,861,종로구
6,용산서,3820,2483,5,5,14,14,194,173,1557,587,2050,1704,용산구
7,성북서,2237,1498,2,2,2,1,86,71,953,409,1194,1015,성북구
8,동대문서,4720,3205,5,5,13,13,173,146,1981,814,2548,2227,동대문구
9,마포서,5854,3597,8,8,14,10,294,247,2555,813,2983,2519,마포구
10,영등포서,6867,4154,14,12,22,20,295,183,2964,978,3572,2961,영등포구
11,성동서,3358,2123,4,4,9,8,126,119,1607,597,1612,1395,성동구
12,동작서,4074,2397,5,5,9,5,285,139,1865,661,1910,1587,동작구
13,광진서,5909,3707,4,4,14,26,240,220,3026,1277,2625,2180,광진구
14,서부서,2085,1393,2,2,2,1,70,59,819,293,1192,1038,은평구
15,강북서,4257,3113,7,8,14,13,153,126,1434,618,2649,2348,강북구
16,금천서,3781,2796,3,4,6,6,151,122,1567,888,2054,1776,금천구
17,중랑서,5193,3405,13,12,11,9,187,148,2135,829,2847,2407,중랑구
18,강남서,5194,3370,3,3,15,12,300,225,2411,984,2465,2146,강남구
19,관악서,6345,3712,9,8,12,14,320,221,2706,827,3298,2642,관악구
20,강서서,5585,4190,7,8,13,13,262,191,2096,1260,3207,2718,강서구
21,강동서,5244,3171,4,3,6,8,156,123,2366,789,2712,2248,강동구
22,종암서,1917,1231,3,3,3,3,64,53,832,332,1015,840,성북구
23,구로서,5646,3502,8,6,15,11,281,164,2335,889,3007,2432,구로구
24,서초서,4183,2714,7,4,8,5,334,193,1982,905,1852,1607,서초구
25,양천서,4528,2815,3,5,6,3,120,105,1890,672,2509,2030,양천구
26,송파서,6778,4113,11,10,13,10,220,178,3239,1129,3295,2786,송파구
27,노원서,5130,3268,10,10,7,7,197,121,2193,801,2723,2329,노원구
28,방배서,1261,736,1,2,1,1,59,56,653,186,547,491,서초구
29,은평서,2660,1774,1,1,7,5,96,82,1095,418,1461,1268,은평구
30,도봉서,2664,1900,3,3,9,10,102,106,1063,478,1487,1303,도봉구
31,수서서,3423,2362,10,7,6,6,149,124,1439,666,1819,1559,강남구

In [19]:
# pivot_table 을 사용하여 관서별 데이터를 구별 데이터로 변경하고, 같은 구의 경우에는 sum을 적용하여 더해주세요. (index : 관서명 -> 구별)
df3 = pd.pivot_table(df2,
                     index = '구별',
                     aggfunc = "sum") #구별 컬럼을 index로 지정. 문제마다 데이터 프레임을 구분하여 각 문제마다 독립적으로 사용. 
df3 = df3.drop('관서명', axis =1) #기존 관서명 컬럼 제거. 
df3 = df3.groupby('구별').sum() #구별로 묶어서 같은 컬럼 값끼리 합을 출력.
df3

,강간(검거),강간(발생),강도(검거),강도(발생),살인(검거),살인(발생),소계(검거),소계(발생),절도(검거),절도(발생),폭력(검거),폭력(발생)
구별,,,,,,,,,,,,
강남구,349,449,18,21,10,13,5732,8617,1650,3850,3705,4284
강동구,123,156,8,6,3,4,3171,5244,789,2366,2248,2712
강북구,126,153,13,14,8,7,3113,4257,618,1434,2348,2649
강서구,191,262,13,13,8,7,4190,5585,1260,2096,2718,3207
관악구,221,320,14,12,8,9,3712,6345,827,2706,2642,3298
광진구,220,240,26,14,4,4,3707,5909,1277,3026,2180,2625
구로구,164,281,11,15,6,8,3502,5646,889,2335,2432,3007
구없음,5069,5449,257,276,156,163,82680,126401,21842,55307,55356,65206
금천구,122,151,6,6,4,3,2796,3781,888,1567,1776,2054
노원구,121,197,7,7,10,10,3268,5130,801,2193,2329,2723
도봉구,106,102,10,9,3,3,1900,2664,478,1063,1303,1487
동대문구,146,173,13,13,5,5,3205,4720,814,1981,2227,2548
동작구,139,285,5,9,5,5,2397,4074,661,1865,1587,1910
마포구,247,294,10,14,8,8,3597,5854,813,2555,2519,2983
서대문구,124,154,4,5,2,2,2579,4029,738,1812,1711,2056
서초구,249,393,6,9,6,8,3450,5444,1091,2635,2098,2399
성동구,119,126,8,9,4,4,2123,3358,597,1607,1395,1612
성북구,124,150,4,5,5,5,2729,4154,741,1785,1855,2209
송파구,178,220,10,13,10,11,4113,6778,1129,3239,2786,3295
양천구,105,120,3,6,5,3,2815,4528,672,1890,2030,2509
영등포구,183,295,20,22,12,14,4154,6867,978,2964,2961,3572
용산구,173,194,14,14,5,5,2483,3820,587,1557,1704,2050
은평구,141,166,6,9,3,3,3167,4745,711,1914,2306,2653
종로구,161,211,9,11,5,6,2943,4705,837,2184,1931,2293
중구,111,170,6,9,2,3,2942,4954,859,2548,1964,2224
중랑구,148,187,9,11,12,13,3405,5193,829,2135,2407,2847

In [9]:
# 4. 구 없음  행은 drop 을 활용하여 삭제해주세요.
df4= df3.copy() #문제마다 데이터 프레임을 구분하여 각 문제마다 독립적으로 사용. 
df4 = df4.drop('구없음', axis =0) #'구없음' 행을 제거. 
df4

,소계(발생),소계(검거),살인(발생),살인(검거),강도(발생),강도(검거),강간(발생),강간(검거),절도(발생),절도(검거),폭력(발생),폭력(검거)
구별,,,,,,,,,,,,
강남구,8617,5732,13,10,21,18,449,349,3850,1650,4284,3705
강동구,5244,3171,4,3,6,8,156,123,2366,789,2712,2248
강북구,4257,3113,7,8,14,13,153,126,1434,618,2649,2348
강서구,5585,4190,7,8,13,13,262,191,2096,1260,3207,2718
관악구,6345,3712,9,8,12,14,320,221,2706,827,3298,2642
광진구,5909,3707,4,4,14,26,240,220,3026,1277,2625,2180
구로구,5646,3502,8,6,15,11,281,164,2335,889,3007,2432
금천구,3781,2796,3,4,6,6,151,122,1567,888,2054,1776
노원구,5130,3268,10,10,7,7,197,121,2193,801,2723,2329
도봉구,2664,1900,3,3,9,10,102,106,1063,478,1487,1303
동대문구,4720,3205,5,5,13,13,173,146,1981,814,2548,2227
동작구,4074,2397,5,5,9,5,285,139,1865,661,1910,1587
마포구,5854,3597,8,8,14,10,294,247,2555,813,2983,2519
서대문구,4029,2579,2,2,5,4,154,124,1812,738,2056,1711
서초구,5444,3450,8,6,9,6,393,249,2635,1091,2399,2098
성동구,3358,2123,4,4,9,8,126,119,1607,597,1612,1395
성북구,4154,2729,5,5,5,4,150,124,1785,741,2209,1855
송파구,6778,4113,11,10,13,10,220,178,3239,1129,3295,2786
양천구,4528,2815,3,5,6,3,120,105,1890,672,2509,2030
영등포구,6867,4154,14,12,22,20,295,183,2964,978,3572,2961
용산구,3820,2483,5,5,14,14,194,173,1557,587,2050,1704
은평구,4745,3167,3,3,9,6,166,141,1914,711,2653,2306
종로구,4705,2943,6,5,11,9,211,161,2184,837,2293,1931
중구,4954,2942,3,2,9,6,170,111,2548,859,2224,1964
중랑구,5193,3405,13,12,11,9,187,148,2135,829,2847,2407

In [21]:
# 5. 각 범죄 별로 검거율을 계산하고, 각 검거율 데이터 column을 DataFrame에 추가해주세요.
df5 = df4.copy() #문제마다 데이터 프레임을 구분하여 각 문제마다 독립적으로 사용. 
crime_list = ['살인','강도','강간','절도','폭력'] #반복문에서 사용하기 위한 범죄 종류.

#검거율 컬럼 생성.
i = '소계' #반복 줄이기 위한 호출변수
df5['검거율'] = df5[f'{i}(검거)']/df5[f'{i}(발생)']*100
#반복문을 이용한 범죄에 따른 검거율 컬럼 생성
for i in crime_list:
    df5[f'{i}검거율'] = df5[f'{i}(검거)']/df5[f'{i}(발생)']

df5

,소계(발생),소계(검거),살인(발생),살인(검거),강도(발생),강도(검거),강간(발생),강간(검거),절도(발생),절도(검거),폭력(발생),폭력(검거),검거율,살인검거율,강도검거율,강간검거율,절도검거율,폭력검거율
구별,,,,,,,,,,,,,,,,,,
강남구,8617,5732,13,10,21,18,449,349,3850,1650,4284,3705,66.519670,0.769231,0.857143,0.777283,0.428571,0.864846
강동구,5244,3171,4,3,6,8,156,123,2366,789,2712,2248,60.469108,0.750000,1.333333,0.788462,0.333474,0.828909
강북구,4257,3113,7,8,14,13,153,126,1434,618,2649,2348,73.126615,1.142857,0.928571,0.823529,0.430962,0.886372
강서구,5585,4190,7,8,13,13,262,191,2096,1260,3207,2718,75.022381,1.142857,1.000000,0.729008,0.601145,0.847521
관악구,6345,3712,9,8,12,14,320,221,2706,827,3298,2642,58.502758,0.888889,1.166667,0.690625,0.305617,0.801092
광진구,5909,3707,4,4,14,26,240,220,3026,1277,2625,2180,62.734811,1.000000,1.857143,0.916667,0.422009,0.830476
구로구,5646,3502,8,6,15,11,281,164,2335,889,3007,2432,62.026213,0.750000,0.733333,0.583630,0.380728,0.808780
금천구,3781,2796,3,4,6,6,151,122,1567,888,2054,1776,73.948691,1.333333,1.000000,0.807947,0.566688,0.864654
노원구,5130,3268,10,10,7,7,197,121,2193,801,2723,2329,63.703704,1.000000,1.000000,0.614213,0.365253,0.855307
도봉구,2664,1900,3,3,9,10,102,106,1063,478,1487,1303,71.321321,1.000000,1.111111,1.039216,0.449671,0.876261
동대문구,4720,3205,5,5,13,13,173,146,1981,814,2548,2227,67.902542,1.000000,1.000000,0.843931,0.410904,0.874019
동작구,4074,2397,5,5,9,5,285,139,1865,661,1910,1587,58.836524,1.000000,0.555556,0.487719,0.354424,0.830890
마포구,5854,3597,8,8,14,10,294,247,2555,813,2983,2519,61.445166,1.000000,0.714286,0.840136,0.318200,0.844452
서대문구,4029,2579,2,2,5,4,154,124,1812,738,2056,1711,64.010921,1.000000,0.800000,0.805195,0.407285,0.832198
서초구,5444,3450,8,6,9,6,393,249,2635,1091,2399,2098,63.372520,0.750000,0.666667,0.633588,0.414042,0.874531
성동구,3358,2123,4,4,9,8,126,119,1607,597,1612,1395,63.222156,1.000000,0.888889,0.944444,0.371500,0.865385
성북구,4154,2729,5,5,5,4,150,124,1785,741,2209,1855,65.695715,1.000000,0.800000,0.826667,0.415126,0.839746
송파구,6778,4113,11,10,13,10,220,178,3239,1129,3295,2786,60.681617,0.909091,0.769231,0.809091,0.348564,0.845524
양천구,4528,2815,3,5,6,3,120,105,1890,672,2509,2030,62.168728,1.666667,0.500000,0.875000,0.355556,0.809087
영등포구,6867,4154,14,12,22,20,295,183,2964,978,3572,2961,60.492209,0.857143,0.909091,0.620339,0.329960,0.828947
용산구,3820,2483,5,5,14,14,194,173,1557,587,2050,1704,65.000000,1.000000,1.000000,0.891753,0.377007,0.831220
은평구,4745,3167,3,3,9,6,166,141,1914,711,2653,2306,66.743941,1.000000,0.666667,0.849398,0.371473,0.869205
종로구,4705,2943,6,5,11,9,211,161,2184,837,2293,1931,62.550478,0.833333,0.818182,0.763033,0.383242,0.842128
중구,4954,2942,3,2,9,6,170,111,2548,859,2224,1964,59.386354,0.666667,0.666667,0.652941,0.337127,0.883094
중랑구,5193,3405,13,12,11,9,187,148,2135,829,2847,2407,65.569035,0.923077,0.818182,0.791444,0.388290,0.845451

In [11]:
# 6.필요없는 column을 del 을 사용하여 삭제해주세요.
df6 = df5.copy() #문제마다 데이터 프레임을 구분하여 각 문제마다 독립적으로 사용. 
delete_list = ['강간(검거)','강도(검거)','살인(검거)','절도(검거)','폭력(검거)','소계(발생)','소계(검거)'] #제거해야 할 컬럼 리스트\
#반복문을 통해 delete_list안의 컬럼을 제거.
for i in delete_list:
    del df6[i]
df6

,살인(발생),강도(발생),강간(발생),절도(발생),폭력(발생),검거율,살인검거율,강도검거율,강간검거율,절도검거율,폭력검거율
구별,,,,,,,,,,,
강남구,13,21,449,3850,4284,0.665197,0.769231,0.857143,0.777283,0.428571,0.864846
강동구,4,6,156,2366,2712,0.604691,0.750000,1.333333,0.788462,0.333474,0.828909
강북구,7,14,153,1434,2649,0.731266,1.142857,0.928571,0.823529,0.430962,0.886372
강서구,7,13,262,2096,3207,0.750224,1.142857,1.000000,0.729008,0.601145,0.847521
관악구,9,12,320,2706,3298,0.585028,0.888889,1.166667,0.690625,0.305617,0.801092
광진구,4,14,240,3026,2625,0.627348,1.000000,1.857143,0.916667,0.422009,0.830476
구로구,8,15,281,2335,3007,0.620262,0.750000,0.733333,0.583630,0.380728,0.808780
금천구,3,6,151,1567,2054,0.739487,1.333333,1.000000,0.807947,0.566688,0.864654
노원구,10,7,197,2193,2723,0.637037,1.000000,1.000000,0.614213,0.365253,0.855307
도봉구,3,9,102,1063,1487,0.713213,1.000000,1.111111,1.039216,0.449671,0.876261
동대문구,5,13,173,1981,2548,0.679025,1.000000,1.000000,0.843931,0.410904,0.874019
동작구,5,9,285,1865,1910,0.588365,1.000000,0.555556,0.487719,0.354424,0.830890
마포구,8,14,294,2555,2983,0.614452,1.000000,0.714286,0.840136,0.318200,0.844452
서대문구,2,5,154,1812,2056,0.640109,1.000000,0.800000,0.805195,0.407285,0.832198
서초구,8,9,393,2635,2399,0.633725,0.750000,0.666667,0.633588,0.414042,0.874531
성동구,4,9,126,1607,1612,0.632222,1.000000,0.888889,0.944444,0.371500,0.865385
성북구,5,5,150,1785,2209,0.656957,1.000000,0.800000,0.826667,0.415126,0.839746
송파구,11,13,220,3239,3295,0.606816,0.909091,0.769231,0.809091,0.348564,0.845524
양천구,3,6,120,1890,2509,0.621687,1.666667,0.500000,0.875000,0.355556,0.809087
영등포구,14,22,295,2964,3572,0.604922,0.857143,0.909091,0.620339,0.329960,0.828947
용산구,5,14,194,1557,2050,0.650000,1.000000,1.000000,0.891753,0.377007,0.831220
은평구,3,9,166,1914,2653,0.667439,1.000000,0.666667,0.849398,0.371473,0.869205
종로구,6,11,211,2184,2293,0.625505,0.833333,0.818182,0.763033,0.383242,0.842128
중구,3,9,170,2548,2224,0.593864,0.666667,0.666667,0.652941,0.337127,0.883094
중랑구,13,11,187,2135,2847,0.655690,0.923077,0.818182,0.791444,0.388290,0.845451

In [12]:
# 7. DataFrame의 컬럼명을 rename 을 사용하여 변경해주세요.
df7 = df6.copy() #문제마다 데이터 프레임을 구분하여 각 문제마다 독립적으로 사용. 
df7 = df7.rename(columns={'강간(발생)':'강간','강도(발생)':'강도','살인(발생)':'살인','절도(발생)':'절도','폭력(발생)':'폭력'}) #컬럼 명 변경
df7

,살인,강도,강간,절도,폭력,검거율,살인검거율,강도검거율,강간검거율,절도검거율,폭력검거율
구별,,,,,,,,,,,
강남구,13,21,449,3850,4284,0.665197,0.769231,0.857143,0.777283,0.428571,0.864846
강동구,4,6,156,2366,2712,0.604691,0.750000,1.333333,0.788462,0.333474,0.828909
강북구,7,14,153,1434,2649,0.731266,1.142857,0.928571,0.823529,0.430962,0.886372
강서구,7,13,262,2096,3207,0.750224,1.142857,1.000000,0.729008,0.601145,0.847521
관악구,9,12,320,2706,3298,0.585028,0.888889,1.166667,0.690625,0.305617,0.801092
광진구,4,14,240,3026,2625,0.627348,1.000000,1.857143,0.916667,0.422009,0.830476
구로구,8,15,281,2335,3007,0.620262,0.750000,0.733333,0.583630,0.380728,0.808780
금천구,3,6,151,1567,2054,0.739487,1.333333,1.000000,0.807947,0.566688,0.864654
노원구,10,7,197,2193,2723,0.637037,1.000000,1.000000,0.614213,0.365253,0.855307
도봉구,3,9,102,1063,1487,0.713213,1.000000,1.111111,1.039216,0.449671,0.876261
동대문구,5,13,173,1981,2548,0.679025,1.000000,1.000000,0.843931,0.410904,0.874019
동작구,5,9,285,1865,1910,0.588365,1.000000,0.555556,0.487719,0.354424,0.830890
마포구,8,14,294,2555,2983,0.614452,1.000000,0.714286,0.840136,0.318200,0.844452
서대문구,2,5,154,1812,2056,0.640109,1.000000,0.800000,0.805195,0.407285,0.832198
서초구,8,9,393,2635,2399,0.633725,0.750000,0.666667,0.633588,0.414042,0.874531
성동구,4,9,126,1607,1612,0.632222,1.000000,0.888889,0.944444,0.371500,0.865385
성북구,5,5,150,1785,2209,0.656957,1.000000,0.800000,0.826667,0.415126,0.839746
송파구,11,13,220,3239,3295,0.606816,0.909091,0.769231,0.809091,0.348564,0.845524
양천구,3,6,120,1890,2509,0.621687,1.666667,0.500000,0.875000,0.355556,0.809087
영등포구,14,22,295,2964,3572,0.604922,0.857143,0.909091,0.620339,0.329960,0.828947
용산구,5,14,194,1557,2050,0.650000,1.000000,1.000000,0.891753,0.377007,0.831220
은평구,3,9,166,1914,2653,0.667439,1.000000,0.666667,0.849398,0.371473,0.869205
종로구,6,11,211,2184,2293,0.625505,0.833333,0.818182,0.763033,0.383242,0.842128
중구,3,9,170,2548,2224,0.593864,0.666667,0.666667,0.652941,0.337127,0.883094
중랑구,13,11,187,2135,2847,0.655690,0.923077,0.818182,0.791444,0.388290,0.845451

In [13]:
#extra 1 Python 라이브러리 함수를 사용하여 인구 데이터(pop_kor.csv) 파일을 불러오고, DataFrame을 출력해주세요.
df_csv = pd.read_csv("pop_kor.csv",index_col= '구별') #csv 불러오기
df_csv

         인구수
구별
강남구   581760
강동구   463321
강북구   334426
강서구   595691
관악구   529031
광진구   375180
구로구   454604
금천구   256167
노원구   578221
도봉구   353241
동대문구  373824
동작구   412774
마포구   398351
서대문구  323105
서초구   451258
성동구   305065
성북구   469560
송파구   667480
양천구   489010
영등포구  417811
용산구   247909
은평구   502578
종로구   163822
중구    134329
중랑구   418620

In [14]:
#extra 2 join 을 사용하여 Quiz에서 수행한 DataFrame과 인구 데이터 DataFrame을 merge하고, DataFrame을 출력해주세요.
extra_df2 = df7.join(df_csv) #df7에 df_csv를 index를 기준으로 결합. 
extra_df2

,살인,강도,강간,절도,폭력,검거율,살인검거율,강도검거율,강간검거율,절도검거율,폭력검거율,인구수
구별,,,,,,,,,,,,
강남구,13,21,449,3850,4284,0.665197,0.769231,0.857143,0.777283,0.428571,0.864846,581760
강동구,4,6,156,2366,2712,0.604691,0.750000,1.333333,0.788462,0.333474,0.828909,463321
강북구,7,14,153,1434,2649,0.731266,1.142857,0.928571,0.823529,0.430962,0.886372,334426
강서구,7,13,262,2096,3207,0.750224,1.142857,1.000000,0.729008,0.601145,0.847521,595691
관악구,9,12,320,2706,3298,0.585028,0.888889,1.166667,0.690625,0.305617,0.801092,529031
광진구,4,14,240,3026,2625,0.627348,1.000000,1.857143,0.916667,0.422009,0.830476,375180
구로구,8,15,281,2335,3007,0.620262,0.750000,0.733333,0.583630,0.380728,0.808780,454604
금천구,3,6,151,1567,2054,0.739487,1.333333,1.000000,0.807947,0.566688,0.864654,256167
노원구,10,7,197,2193,2723,0.637037,1.000000,1.000000,0.614213,0.365253,0.855307,578221
도봉구,3,9,102,1063,1487,0.713213,1.000000,1.111111,1.039216,0.449671,0.876261,353241
동대문구,5,13,173,1981,2548,0.679025,1.000000,1.000000,0.843931,0.410904,0.874019,373824
동작구,5,9,285,1865,1910,0.588365,1.000000,0.555556,0.487719,0.354424,0.830890,412774
마포구,8,14,294,2555,2983,0.614452,1.000000,0.714286,0.840136,0.318200,0.844452,398351
서대문구,2,5,154,1812,2056,0.640109,1.000000,0.800000,0.805195,0.407285,0.832198,323105
서초구,8,9,393,2635,2399,0.633725,0.750000,0.666667,0.633588,0.414042,0.874531,451258
성동구,4,9,126,1607,1612,0.632222,1.000000,0.888889,0.944444,0.371500,0.865385,305065
성북구,5,5,150,1785,2209,0.656957,1.000000,0.800000,0.826667,0.415126,0.839746,469560
송파구,11,13,220,3239,3295,0.606816,0.909091,0.769231,0.809091,0.348564,0.845524,667480
양천구,3,6,120,1890,2509,0.621687,1.666667,0.500000,0.875000,0.355556,0.809087,489010
영등포구,14,22,295,2964,3572,0.604922,0.857143,0.909091,0.620339,0.329960,0.828947,417811
용산구,5,14,194,1557,2050,0.650000,1.000000,1.000000,0.891753,0.377007,0.831220,247909
은평구,3,9,166,1914,2653,0.667439,1.000000,0.666667,0.849398,0.371473,0.869205,502578
종로구,6,11,211,2184,2293,0.625505,0.833333,0.818182,0.763033,0.383242,0.842128,163822
중구,3,9,170,2548,2224,0.593864,0.666667,0.666667,0.652941,0.337127,0.883094,134329
중랑구,13,11,187,2135,2847,0.655690,0.923077,0.818182,0.791444,0.388290,0.845451,418620

In [15]:
extra_df3 = extra_df2.copy() #문제마다 데이터 프레임을 구분하여 각 문제마다 독립적으로 사용. 
extra_df3 = extra_df3.sort_values('검거율',ascending= True) #검거율 기준으로 오름차순 정렬
extra_df3

,살인,강도,강간,절도,폭력,검거율,살인검거율,강도검거율,강간검거율,절도검거율,폭력검거율,인구수
구별,,,,,,,,,,,,
관악구,9,12,320,2706,3298,0.585028,0.888889,1.166667,0.690625,0.305617,0.801092,529031
동작구,5,9,285,1865,1910,0.588365,1.000000,0.555556,0.487719,0.354424,0.830890,412774
중구,3,9,170,2548,2224,0.593864,0.666667,0.666667,0.652941,0.337127,0.883094,134329
강동구,4,6,156,2366,2712,0.604691,0.750000,1.333333,0.788462,0.333474,0.828909,463321
영등포구,14,22,295,2964,3572,0.604922,0.857143,0.909091,0.620339,0.329960,0.828947,417811
송파구,11,13,220,3239,3295,0.606816,0.909091,0.769231,0.809091,0.348564,0.845524,667480
마포구,8,14,294,2555,2983,0.614452,1.000000,0.714286,0.840136,0.318200,0.844452,398351
구로구,8,15,281,2335,3007,0.620262,0.750000,0.733333,0.583630,0.380728,0.808780,454604
양천구,3,6,120,1890,2509,0.621687,1.666667,0.500000,0.875000,0.355556,0.809087,489010
종로구,6,11,211,2184,2293,0.625505,0.833333,0.818182,0.763033,0.383242,0.842128,163822
광진구,4,14,240,3026,2625,0.627348,1.000000,1.857143,0.916667,0.422009,0.830476,375180
성동구,4,9,126,1607,1612,0.632222,1.000000,0.888889,0.944444,0.371500,0.865385,305065
서초구,8,9,393,2635,2399,0.633725,0.750000,0.666667,0.633588,0.414042,0.874531,451258
노원구,10,7,197,2193,2723,0.637037,1.000000,1.000000,0.614213,0.365253,0.855307,578221
서대문구,2,5,154,1812,2056,0.640109,1.000000,0.800000,0.805195,0.407285,0.832198,323105
용산구,5,14,194,1557,2050,0.650000,1.000000,1.000000,0.891753,0.377007,0.831220,247909
중랑구,13,11,187,2135,2847,0.655690,0.923077,0.818182,0.791444,0.388290,0.845451,418620
성북구,5,5,150,1785,2209,0.656957,1.000000,0.800000,0.826667,0.415126,0.839746,469560
강남구,13,21,449,3850,4284,0.665197,0.769231,0.857143,0.777283,0.428571,0.864846,581760
은평구,3,9,166,1914,2653,0.667439,1.000000,0.666667,0.849398,0.371473,0.869205,502578
동대문구,5,13,173,1981,2548,0.679025,1.000000,1.000000,0.843931,0.410904,0.874019,373824
도봉구,3,9,102,1063,1487,0.713213,1.000000,1.111111,1.039216,0.449671,0.876261,353241
강북구,7,14,153,1434,2649,0.731266,1.142857,0.928571,0.823529,0.430962,0.886372,334426
금천구,3,6,151,1567,2054,0.739487,1.333333,1.000000,0.807947,0.566688,0.864654,256167
강서구,7,13,262,2096,3207,0.750224,1.142857,1.000000,0.729008,0.601145,0.847521,595691